version: "3"

services:
  api9:
    container_name: api9
    restart: unless-stopped
    build:
      context: ./
    ports:
      - 0.0.0.0:8000:${PORT}
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "2"
    command: "python start.py"